### ISSUE TITLE
tail-AA icon excessively large

### ISSUE THREAD

**Issue by MattSidor** [AlaskaAirlines/Icons#105]
**Describe the bug**
The `logos/tail-AA.svg` icon is excessively large (455 KB) and contains complex and hidden vectors which are not visible due to a masking layer effect. The next largest tail icon, `logos/tail-AS.svg` (Alaska), is only 34 KB.

**To Reproduce**
1. Open the file in Adobe Illustrator or similar vector illustration program
2. Select the vectors to make them visible. Note the portions of vectors that are not visible due to masking, and also note the high complexity / number of vectors which are visible.

**Screenshots**
![Screen Shot 2021-12-17 at 4 18 52 PM](https://user-images.githubusercontent.com/6138182/147510835-fc73a29b-4f0d-4e0c-8b6c-dc513fbba41b.png)

**Additional context**
I think this may have been traced before masking from a raster image similar to this one: https://www.malaysiaairlines.com/content/dam/mas/experience/oneworld/tail/tailfin-americanairlines.png

The complexity / number of the vectors seems to stem from the sheen / color gradient effects on the source image. I wonder if these effects can be reproduced with simpler / fewer vectors, perhaps through experimentation with the raster image tracing settings in Adobe Illustrator or similar program.

I tried futzing around with this in Illustrator, but I'm a novice and couldn't figure out the best way to accomplish this. I'm hoping that someone with more experience can try instead.

**Comment by blackfalcon** [comment]
Melissa Gesford
Wed 3/30/2022 11:44 AM
Hey!  Quick answer on this one. 

No concerns on our side to simplify. If you can reduce and keep a bit of the gradient even better. 

Thanks!

**Comment by blackfalcon** [comment]
Message was sent to the design team to export an updated version of the SVG.

**Comment by tombauer85** [comment]
@blackfalcon please use the attached SVG in place of what is currently used for the **one**world page.
[tail-AA.svg.zip](https://github.com/AlaskaAirlines/Icons/files/8477299/tail-AA.svg.zip)
