### ISSUE TITLE
New sparkle-stroke icon contains flawed references

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/Icons#118]
## Describe the bug

The `sparkle-stroke.svg` file contains an illegal reference `mask="url(#path-1-inside-1_920_5084)"` that when run caused the Alaska Credit Card icon to fail. 

## Expected behavior

All icons need to render correctly.

**Comment by KaylaBlyton1** [comment]
Here is a re-exported sparkle-stroke. I renamed one of the layers in hopes that it will help resolve the issue at hand.
![sparkle-stroke](https://user-images.githubusercontent.com/83242595/165158116-ac0b570d-2fb1-4934-8db4-38310fb80a31.svg)

**Comment by blackfalcon** [comment]
@KaylaBlyton1 do you know what is creating a mask over the icon? I believe that is where the issue is coming from.

When I remove the code in the SVG that creates the mask over the image, I get the following. It's this mask that is causing the issue. 

<img width="126" alt="Screen Shot 2022-04-25 at 4 13 55 PM" src="https://user-images.githubusercontent.com/181089/165189398-71ca53d5-17a7-4162-ab38-44f2e50325a7.png">

**Comment by blackfalcon** [comment]
This icon is proving to be a trick. This SVG is making use of a stroke and fill to create the shape. This is causing issues on how we process the icons for use. But looking at the star-stroke icon, this is just the shape, not stroke and fill. Can the sparkle-stroke be updated to be like the star?

<img width="678" alt="Screen Shot 2022-04-29 at 11 30 48 AM" src="https://user-images.githubusercontent.com/181089/166003718-1f5abeed-2edb-438c-bd48-b2eab7d64d76.png">

**Comment by KaylaBlyton1** [comment]
@blackfalcon Thank you for explaining! The star example was very helpful. I have flattened this icon into oblivion - it SHOULD work now.
![sparkle-stroke](https://user-images.githubusercontent.com/83242595/166311544-8a9305c5-601c-4d44-a60c-6ec482f37115.svg)

**Comment by KaylaBlyton1** [comment]
OK... 4th time is the charm?! @blackfalcon 
![sparkle-stroke](https://user-images.githubusercontent.com/83242595/166573946-19ef7120-dfb4-40f0-abfc-c48555930309.svg)

**Comment by KaylaBlyton1** [comment]
@blackfalcon I reached out to June, but in the meantime I tried one more thing. Let me know if this works? Strokes are outlined, flattened, and I double checked and there are no masks in the layers. 
![sparkle-stroke](https://user-images.githubusercontent.com/83242595/166800139-4c6f9fbf-2952-406d-a433-05ff0bc0d6a7.svg)

**Comment by blackfalcon** [comment]
@KaylaBlyton1 WE HAVE A WINNER! 

<img width="695" alt="Screen Shot 2022-05-05 at 8 16 14 AM" src="https://user-images.githubusercontent.com/181089/166955914-fb12c17e-8661-404d-8e3f-731b1463d37f.png">

Whatever was learned from this, can you work with @leeejune to be sure to document this?
