### ISSUE TITLE
Add support for TypeScript

### ISSUE THREAD

**Issue by kaityama** [AlaskaAirlines/Icons#121]
**Is your feature request related to a problem? Please describe.**
Out of the box, icons are incompatible with TypeScript (TS). With some teams choosing to go the TS route when working with the open-wc generator, the developer experience could be improved by adding support for TS in all Auro icons.

**Describe the solution you'd like**
When importing an icon into my TS web component, I shouldn't get any errors in my IDE and when transpiled, the component including the icon should render properly in the browser. This should work right out of the box.

**Describe alternatives you've considered**
For the time being, @geoffrich and I have found a work around, which is creating a `d.ts` file in your project where you can add your type definitions.

```
declare module "@alaskaairux/icons/dist/icons/interface/star-filled_es6" {
    const svg: string;  
}
```

Here I've included the type definition for `svg` from the `star-filled` icon.

Repro steps:

Generate a web component
`npm init @open-wc`

Choose the following menu options:
```
What would you like to do today: Scaffold a new project
What would you like to scaffold: Web Component
What would you like to add: Demoing
TypeScript: yes
Tag name of your web component: icon-test
```

Install @alaskaairux/icons
`npm i @alaskaairux/icons`

Add the icon import to the component

icon-test.ts
```
import {html, css, LitElement} from 'lit';
import { unsafeSVG } from 'lit/directives/unsafe-svg.js';
import star from '@alaskaairux/icons/dist/icons/interface/star-filled_es6';

export class IconTest extends LitElement {
  static styles = css`
      .icon { 
        color: rebeccapurple; 
      }`
  render() {
    return html`<p>Hello! <span class="icon">${unsafeSVG(star.svg)}</span></p>`;
  }
}
customElements.define('icon-test', IconTest);
```

index.html
```
<!DOCTYPE html>
<html lang="en-GB">
  <head>
    <link rel="stylesheet" href="https://unpkg.com/@alaskaairux/design-tokens@3.8.0/dist/tokens/CSSCustomProperties.css">
  </head>
  <body>
    <div id="demo"></div>

    <script type="module">
      import { html, render } from 'lit';
      import '../dist/src/icon-test.js';

      render(
        html` <icon-test> </icon-test> `,
        document.querySelector('#demo')
      );
    </script>
  </body>
</html>
```

d.ts
```
declare module "@alaskaairux/icons/dist/icons/interface/star-filled_es6" {
    const svg: string;  
}
```

**Comment by kaityama** [comment]
> If I am understanding this correctly, what you are looking for is a d.ts file that contains the following for ALL of the icons in the resource?
> 
> ```js
> declare module "@alaskaairux/icons/dist/icons/interface/star-filled_es6" {
>     const svg: string;  
> }
> ```
> 
> Question: is anything else required other than having this .d.ts file in the ./dist directory of the package?

I'm not sure what the best solution for this would be. But I was hoping there would be TypeScript support on the Icons end that we wouldn't need a `d.ts` file on our end.

**Comment by geoffrich** [comment]
This will also provide better auto-complete for all users, not just those using TS. For example, I now get better suggestions in VSCode in a regular JS file.

![image](https://user-images.githubusercontent.com/4992896/165581705-701d1933-87ca-4997-957b-5e852770be09.png)

**Comment by blackfalcon** [comment]
@geoffrich generating is not the issue. I did something similar with auro-input https://github.com/AlaskaAirlines/auro-input/compare/main...dsande/tsTypesSpike

The question that I can't seem to come to is; I can generate this and put it in the `./dist` dir, but then what? I can't seem to get a consistent answer on how this is consumed? 

Does the IDE/project simply pick up this file reference? Is there an additional step to get this referenced in the project? If there is an additional step, who's responsible for that? I will generate .d.ts files all day long, but if I don't know why they are to be consumed, then I am just asking for trouble. 

If you have recommendations, that would be great.

**Comment by geoffrich** [comment]
If I'm reading [the TS docs](https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html#editing-the-packagejson) correctly, if we output the types in the `dist` directory everything should work.

We specify `"main": "dist/index.js",` in the `package.json`, so TS will infer that the types are located at `dist/index.d.ts`:

![image](https://user-images.githubusercontent.com/4992896/165822244-0af8a355-efca-44d5-8639-0890d21e5a0d.png)

If you don't mind, I can just assign this to myself - I think I know what to do and can verify.
