### ISSUE TITLE
Air Tahiti Nui (TN) Tail

### ISSUE THREAD

**Issue by KaylaBlyton1** [AlaskaAirlines/Icons#126]
# Add new icon(s) to the library

> Please fill out the table below with the desired information per icon

| name | category | description |
|---|---|---|
|  |  |  |

## Icon art

> The icon(s) per this request, has the new art been completed?

- [x] Yes
- [ ] No

> If YES, does the new icon art follow all the recommendations from the [Auro Icon Design Guidelines](https://auro.alaskaair.com/foundations/iconography/design-guidelines)?

- [x] Yes
- [ ] No

> If YES, the icon(s) in the request, have they been added to the UiKit Abstract repo?

- [x] Yes
- [ ] No

### Attach exported SVG files to this issue
![tail-TN](https://user-images.githubusercontent.com/83242595/174179162-152436cb-71fd-4c3c-a8d0-ee7347261a51.svg)

See the options below for attaching a file to this request.

**Comment by blackfalcon** [comment]
@braven112 is this a candidate for educational dev?

**Comment by MattSidor** [comment]
New logo added with PR #128
