### ISSUE TITLE
Condor CFG (Updated) and Mokulele FDY Tail Art

### ISSUE THREAD

**Issue by KaylaBlyton1** [AlaskaAirlines/Icons#133]
# Add new icon(s) to the library

> Please fill out the table below with the desired information per icon

| name | category | description |
|---|---|---|
|  |  |  |

## Icon art

> The icon(s) per this request, has the new art been completed?

- [x] Yes
- [ ] No

> If YES, does the new icon art follow all the recommendations from the [Auro Icon Design Guidelines](https://auro.alaskaair.com/foundations/iconography/design-guidelines)?

- [x] Yes
- [ ] No

> If YES, the icon(s) in the request, have they been added to the UiKit Abstract repo?

- [x] Yes
- [ ] No

### Attach exported SVG files to this issue

![Condor_Updated](https://user-images.githubusercontent.com/83242595/181129748-ed93163a-a6f0-402c-ade4-6c21ae3b36c0.svg)
![Mokulele](https://user-images.githubusercontent.com/83242595/181129758-37e41a43-f1de-4988-bc86-a91dc7286c72.svg)

See the options below for attaching a file to this request.

**Comment by KaylaBlyton1** [comment]
@leeejune Submitted an issue here per our convo! :)

**Comment by blackfalcon** [comment]
Once released, the icon/tail sticker sheet needs to be updated.  See @blackfalcon for details.
