### ISSUE TITLE
Discrepancy between icon sizing in design vs development

### ISSUE THREAD

**Issue by KaylaBlyton1** [AlaskaAirlines/Icons#141]
**Describe the bug**
In design, we call the icons, sm, md, lg. But when engineers go to size it, they are setting a customSize attribute using a design token of --auro-size-lg or whatever it may be. The discrepancy is that --auro-size-md = 16px which in design guidelines, is a small icon

**To Reproduce**
1. Design icon guidelines page: https://auro.alaskaair.com/icons/guidelines
2. Dev icon guidelines page: https://auro.alaskaair.com/components/auro/icon

**Expected behavior**
I expect that the sizes of icons between design and development to be the same - possibly, this just means updating the labels on the doc site.

**Comment by blackfalcon** [comment]
With SVGs there is a baseline size, `24px` that is dictated in the file.

https://github.com/AlaskaAirlines/Icons/blob/c2e6ef41c8b64ea05f377956908eb6c482476b24/src/data/icons.json#L8-L9

SVGs are also flexible so engineers have the ability to change the size and color of the SVG. Auro cannot specifically dictate a size as this will limit its use. 

The auro-icon element was designed to maintain the size consistency. 

Interestingly enough, neither Auro Icons nor the `auro-icon` element has the concept of `sm`, `md`, or `lg`. There is the baseline `24px` or `auro-icon` supports a `customSize` attribute. 

Can you point to any examples where this issue appears in production?

**Comment by KaylaBlyton1** [comment]
@erikalanghauser Looping back around to this - can you point to where the issue is in production for @blackfalcon?

**Comment by blackfalcon** [comment]
This issue has been labeled as `abandoned` as there has not been any feedback since October of 2022. Unless there is additional information submitted as to the root cause of the issue, this issue will be closed in 30 days.
