### ISSUE TITLE
Latam Tail Update (aligning with brand colors)

### ISSUE THREAD

**Issue by KaylaBlyton1** [AlaskaAirlines/Icons#142]
# Add new icon(s) to the library

> Please fill out the table below with the desired information per icon

| name | category | description |
|---|---|---|
|  |  |  |

## Icon art
![LATAM](https://user-images.githubusercontent.com/83242595/194676653-f89ab5ef-9b4e-4b97-8556-4bfe0cc66999.svg)

> The icon(s) per this request, has the new art been completed?

- [x] Yes
- [ ] No

> If YES, does the new icon art follow all the recommendations from the [Auro Icon Design Guidelines](https://auro.alaskaair.com/foundations/iconography/design-guidelines)?

- [x] Yes
- [ ] No

> If YES, the icon(s) in the request, have they been added to the UiKit Abstract repo?

- [x] Yes
- [ ] No

### Attach exported SVG files to this issue

See the options below for attaching a file to this request.

**Comment by KaylaBlyton1** [comment]
@leeejune Here is the updated tail art!

**Comment by blackfalcon** [comment]
Is this a replacement of these two tails? 

<img width="532" alt="Screen Shot 2022-10-10 at 7 48 05 PM" src="https://user-images.githubusercontent.com/181089/194985661-1b7d5139-760b-44c0-9263-41f800f2dbd9.png">

**Comment by KaylaBlyton1** [comment]
@blackfalcon @leeejune Sorry, Github is attached to my personal email so I forget to respond sometimes.

Yes! This is to replace the current LATAM tail.

**Comment by gusnaughton** [comment]
From the Alliances perspective - what timeframe are we looking at for adding this logo to the DS?

**Comment by blackfalcon** [comment]
@KaylaBlyton1 and @gusnaughton please see PR for status of update.
