### ISSUE TITLE
SVGO dependency outputs warning on install

### ISSUE THREAD

**Issue by mikearche** [AlaskaAirlines/Icons#149]
**Describe the bug**
When installing the dependency SVGO it outputs the warning :
`npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility`

We can fix this by updating the SVGO version to 3.0, but this requires us to be on Node 14.
https://github.com/svg/svgo/releases/tag/v3.0.0

**To Reproduce**
1. Delete your node_modules (if they exist)
2. Do a fresh install of all of the packages `npm i`
3. View the terminal
4. See warning

**Expected behavior**
There should be no warnings when you install dependencies.

**Screenshots**
![image](https://user-images.githubusercontent.com/20789620/201168842-26f0bae5-b563-47f2-8872-439df3d55058.png)

![image](https://user-images.githubusercontent.com/20789620/201168963-9f760421-7d6f-49df-a823-c3efb9d7aa97.png)

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
Developers who install the icons package as a dependency will also receive the warning.

**Comment by blackfalcon** [comment]
Assigned to @mikearche. Feel free to address this update once PR #148 has been addressed.
