### ISSUE TITLE
Generate script does not work on Windows file systems

### ISSUE THREAD

**Issue by mikearche** [AlaskaAirlines/Icons#153]
**Describe the bug**
There are bugs as well as improvements to how we handle paths in our `buildDemo.js` file. I noticed upon running the generate script on my local windows machine that it was unable to locate _any_ of the files for generation.

**To Reproduce**
1. Use a windows file system
2. Run `npm run generate`

**Expected behavior**
The way we handle paths should not be operating system dependent.

**Screenshots**
![image](https://user-images.githubusercontent.com/20789620/202323968-ede6a88b-5aab-4940-ab5f-d4700f003b33.png)

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
Happy to take this issue on as I already have something working locally.

**Comment by blackfalcon** [comment]
The default answer, 99.9997% of all dev with Auro happens on non-Windows machines. https://auro.alaskaair.com/developer-setup/windows

But if you have a fix to submit, we'd love to see it.
