### ISSUE TITLE
Flight details

### ISSUE THREAD

**Issue by josee-alaska** [AlaskaAirlines/Icons#157]
# Add new icon(s) to the library

> Please fill out the table below with the desired information per icon

| name | category | description |
|---|---|---|
| flight-details | terminal | Paragraph wireframe with an upper corner plane drawing |

## Icon art

> The icon(s) per this request, has the new art been completed?

- [x] Yes
- [ ] No

> If YES, does the new icon art follow all the recommendations from the [Auro Icon Design Guidelines](https://auro.alaskaair.com/foundations/iconography/design-guidelines)?

- [x] Yes
- [ ] No

> If YES, the icon(s) in the request, have they been added to the UiKit Abstract repo?

- [ ] Yes
- [x] No

### Attach exported SVG files to this issue

![terminal:flight-details](https://user-images.githubusercontent.com/105021248/203625346-2b4721ec-159f-4d9f-af05-6524eb8cc53b.svg) 

See the options below for attaching a file to this request.

**Comment by leeejune** [comment]
Closing the issue to gather all icons in one issue.
