### ISSUE TITLE
Departure arrow

### ISSUE THREAD

**Issue by josee-alaska** [AlaskaAirlines/Icons#158]
# Add new icon(s) to the library

> Please fill out the table below with the desired information per icon

| name | category | description |
|---|---|---|
| departure-stroke | terminal | An arrow pointed upwards and framed within a rectangle stroke |
| departure-filled | terminal | An arrow pointed upwards and contained within a filled rectangle |

## Icon art

> The icon(s) per this request, has the new art been completed?

- [x] Yes
- [ ] No

> If YES, does the new icon art follow all the recommendations from the [Auro Icon Design Guidelines](https://auro.alaskaair.com/foundations/iconography/design-guidelines)?

- [x] Yes
- [ ] No

> If YES, the icon(s) in the request, have they been added to the UiKit Abstract repo?

- [ ] Yes
- [x] No

### Attach exported SVG files to this issue

![terminal:departure-stroke](https://user-images.githubusercontent.com/105021248/203627008-e44fa141-3d54-44ff-a9db-579371870526.svg)

![terminal:departure-filled](https://user-images.githubusercontent.com/105021248/203627040-1e4534b1-09f8-4841-aeec-d5d49ca1299d.svg)

See the options below for attaching a file to this request.

**Comment by leeejune** [comment]
Closing the issue to gather all icons in one issue.

**Comment by leeejune** [comment]
Closing the issue to gather all icons in one issue.

**Comment by leeejune** [comment]
Closing the issue to gather all icons in one issue.
