### ISSUE TITLE
Arrival arrow

### ISSUE THREAD

**Issue by josee-alaska** [AlaskaAirlines/Icons#159]
# Add new icon(s) to the library

> Please fill out the table below with the desired information per icon

| name | category | description |
|---|---|---|
| arrival-stroke | terminal | An arrow pointed downwards and framed within a rectangle stroke |
| arrival-filled | terminal | An arrow pointed downwards and contained within a filled rectangle |

## Icon art

> The icon(s) per this request, has the new art been completed?

- [x] Yes
- [ ] No

> If YES, does the new icon art follow all the recommendations from the [Auro Icon Design Guidelines](https://auro.alaskaair.com/foundations/iconography/design-guidelines)?

- [x] Yes
- [ ] No

> If YES, the icon(s) in the request, have they been added to the UiKit Abstract repo?

- [ ] Yes
- [x] No

### Attach exported SVG files to this issue

![terminal:arrival-stroke](https://user-images.githubusercontent.com/105021248/203627941-13bfb7c3-58f4-47b8-af39-d27350361883.svg)

![terminal:arrival-filled](https://user-images.githubusercontent.com/105021248/203627960-8edbbc61-5845-4f83-bd54-6e01d327ac12.svg)

See the options below for attaching a file to this request.

**Comment by leeejune** [comment]
Closing the issue to gather all icons in one issue.
