### ISSUE TITLE
Passenger details

### ISSUE THREAD

**Issue by josee-alaska** [AlaskaAirlines/Icons#160]
# Add new icon(s) to the library

> Please fill out the table below with the desired information per icon

| name | category | description |
|---|---|---|
| passenger | in-flight | Avatar within a circle stroke  |

## Icon art

> The icon(s) per this request, has the new art been completed?

- [x] Yes
- [ ] No

> If YES, does the new icon art follow all the recommendations from the [Auro Icon Design Guidelines](https://auro.alaskaair.com/foundations/iconography/design-guidelines)?

- [x] Yes
- [ ] No

> If YES, the icon(s) in the request, have they been added to the UiKit Abstract repo?

- [ ] Yes
- [x] No

### Attach exported SVG files to this issue

![in-flight:passenger](https://user-images.githubusercontent.com/105021248/203629911-fbedc72f-f9a1-4875-abe0-fa4ded3d66b7.svg)

See the options below for attaching a file to this request.

**Comment by leeejune** [comment]
Closing the issue to gather all icons in one issue.
