### ISSUE TITLE
Terminal and in-flight icons

### ISSUE THREAD

**Issue by josee-alaska** [AlaskaAirlines/Icons#161]
# Add new icon(s) to the library

> Please fill out the table below with the desired information per icon

| name | category | description |
|---|---|---|
| multipax | in-flight | Two avatars within a circle stroke |
| flight-details | terminal | Paragraph wireframe with an upper corner plane drawing |
| departure-stroke | terminal | An arrow pointed upwards and framed within a rectangle stroke |
| departure-filled | terminal | An arrow pointed upwards and contained within a filled rectangle |
| arrival-stroke | terminal | An arrow pointed downwards and framed within a rectangle stroke |
| arrival-filled | terminal | An arrow pointed downwards and contained within a filled rectangle |
| passenger | in-flight | Avatar within a circle stroke  |
| diverted | terminal | An arrow pointed to the right with a straight dotted line |

## Icon art

> The icon(s) per this request, has the new art been completed?

- [x] Yes
- [ ] No

> If YES, does the new icon art follow all the recommendations from the [Auro Icon Design Guidelines](https://auro.alaskaair.com/foundations/iconography/design-guidelines)?

- [x] Yes
- [ ] No

> If YES, the icon(s) in the request, have they been added to the UiKit Abstract repo?

- [ ] Yes
- [x] No

### Attach exported SVG files to this issue
![in-flight:multipax](https://user-images.githubusercontent.com/105021248/203665483-e2e1ca09-bb4c-4d92-9dba-55cb977c1f22.svg)

![terminal:flight-details](https://user-images.githubusercontent.com/105021248/203625346-2b4721ec-159f-4d9f-af05-6524eb8cc53b.svg) 

![terminal:departure-stroke](https://user-images.githubusercontent.com/105021248/203627008-e44fa141-3d54-44ff-a9db-579371870526.svg)

![terminal:departure-filled](https://user-images.githubusercontent.com/105021248/203627040-1e4534b1-09f8-4841-aeec-d5d49ca1299d.svg)

![terminal:arrival-stroke](https://user-images.githubusercontent.com/105021248/203627941-13bfb7c3-58f4-47b8-af39-d27350361883.svg)

![terminal:arrival-filled](https://user-images.githubusercontent.com/105021248/203627960-8edbbc61-5845-4f83-bd54-6e01d327ac12.svg)

![in-flight:passenger](https://user-images.githubusercontent.com/105021248/203629911-fbedc72f-f9a1-4875-abe0-fa4ded3d66b7.svg)

![terminal:diverted](https://user-images.githubusercontent.com/55998746/204367976-2a85948d-ed23-4f73-bfa3-3211b3c579f2.svg)

See the options below for attaching a file to this request.

**Comment by blackfalcon** [comment]
Just FYI... it makes this a lot easier if all the icons are named properly and in a ZIP attachment.
