### ISSUE TITLE
Twitter Icon

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/Icons#164]
**Is your feature request related to a problem? Please describe.**
We need an icon for Twitter

**Describe the solution you'd like**
an icon for Twitter

**Describe alternatives you've considered**
not using auro

**Additional context**
Our footer has it but not our design system

**Comment by mikearche** [comment]
We might not need this if we give it a few months 😂

**Comment by braven112** [comment]
I knew that was coming as I was writing this issue 🤣

**Comment by leeejune** [comment]
| name | category | title | description |
|---|---|---|---|
| new-icon | shop | New icon | Icon that represents a new thing |

**Comment by leeejune** [comment]
| name | category | title | description |
|---|---|---|---|
| new-icon | shop | New icon | Icon that represents a new thing |

**Comment by blackfalcon** [comment]
Work issue has been moved to 

- https://github.com/AlaskaAirlines/Icons/issues/187
