### ISSUE TITLE
New Tail: Southern Airways Express

### ISSUE THREAD

**Issue by KaylaBlyton1** [AlaskaAirlines/Icons#174]
# Add new icon(s) to the library

> Please fill out the table below with the desired information per icon. This information must be included with the icon request before it can be accepted.

see the table below for a list of available categories

| category  | description |
|-----------|-------------|
| alert     | Icons used specifically to alert users as to the state of awareness |
| in-flight | icons reserved for 'day of travel' user experiences |
| interface | Icons used to create interface enhancements |
| payment   | Icons specifically to be used in a transaction flow |
| shop      | icons for use with shopping experiences |
| social    | Icons for use with social media |
| terminal  | Icons related to terminal experiences |
| partnership  | Icons related to business partnerships and Alaska Airlines |
| logo  | Logo SVGs, e.g. tails or company logos |

- **Name:** What is the name of the icon? Please update the name of the file to match.
- **Category:** What category of icons will this new icon be listed?
- **Title:** An OPTIONAL description of the icon. ††
- **Description:** Alternative text of the icon that will be read back to assistive technologies.

<small>†† The title is only needed if there is text that you wish to appear in the native browser tooltip functionality. See an example with the [external link](https://auro.alaskaair.com/icons) icon in the **interface** section.</small>

| name | category | title | description |
|---|---|---|---|
|tail-9X|logo|Tail art for Souther Airways Express|Southern Airways Express Airplane Tail Icon|
|  |  |   |  |

## Icon art

> The icon(s) per this request, has the new art been completed?

- [x] Yes
- [ ] No

> If YES, does the new icon art follow all the recommendations from the [Auro Icon Design Guidelines](https://auro.alaskaair.com/foundations/iconography/design-guidelines)?

- [x] Yes
- [ ] No

> If YES, the icon(s) in the request, have they been added to the UiKit Abstract repo?

- [ ] Yes
- [x] No

### Attach exported SVG files to this issue

See the options below for attaching a file to this request.
![SouthernAirwaysExpress_Tail](https://user-images.githubusercontent.com/83242595/212222213-98262d93-6dd2-4c20-892f-487842b6030e.svg)

**Comment by Sandeepchidipudi** [comment]
@blackfalcon  / @leeejune  can you please help us to create a PR for this issue

**Comment by blackfalcon** [comment]
There is already a tail for 9X, is this a replacement? 

<img width="260" alt="Screen Shot 2023-01-17 at 9 11 28 PM" src="https://user-images.githubusercontent.com/181089/213089547-d7504a9d-0bb4-4f18-b2bd-6ac7076a4aef.png">

**Comment by praveen-jakkuva** [comment]
> There is already a tail for 9X, is this a replacement?
> 
> <img alt="Screen Shot 2023-01-17 at 9 11 28 PM" width="260" src="https://user-images.githubusercontent.com/181089/213089547-d7504a9d-0bb4-4f18-b2bd-6ac7076a4aef.png">

Yes, this is a replacement for the 9X tail. Alliances has requested to display the Southern tail as they are the parent company of Mokulele

**Comment by blackfalcon** [comment]
@praveen-jakkuva see previous comment.

**Comment by praveen-jakkuva** [comment]
> @praveen-jakkuva see previous comment.

Can you please tag Tom Bauer as Kayla is on vacation this week

**Comment by tombauer85** [comment]
@praveen-jakkuva and @blackfalcon here is the an SVG for Southern Airways with padding. The tail dimensions are 680px X 654, set within an 856px X 830px frame. Please let me know if this is consistent with the other tail avatars. Thanks
![Southern Airways](https://user-images.githubusercontent.com/79945832/213517236-67facc2c-4308-4cfc-b3b4-e3699d280a38.svg)

**Comment by blackfalcon** [comment]
@tombauer85  New icon added. 

![Screen Shot 2023-01-19 at 5 23 26 PM](https://user-images.githubusercontent.com/181089/213598024-90a11cad-62bd-4533-9710-a00f8f609028.png)
