### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/Icons#178]
## Describe the bug

The documentation only shows the css for the `-webkit-mask-image` vendor prefix but we need to show the standard `mask-image` as well so that it works in firefox and any other browser that supports the css property.

https://github.com/AlaskaAirlines/Icons/blob/master/docs/ways-to-use.md

![Image](https://user-images.githubusercontent.com/5118118/223184354-17b3a62a-dea1-473e-b2d5-d996bf5f839c.png)

https://developer.mozilla.org/en-US/docs/Web/CSS/mask-image

**Comment by blackfalcon** [comment]
This issue has not been though team refinement and unsure why this is already set to READY TO WORK?

**Comment by braven112** [comment]
Some background this one is just a task that is required to finish the bug here: https://github.com/AlaskaAirlines/auro-calendar/issues/37  We'll continue to have this issue if we are telling people to use incomplete code.
