### ISSUE TITLE
Ravn Tail Update

### ISSUE THREAD

**Issue by KaylaBlyton1** [AlaskaAirlines/Icons#179]
# Add new icon(s) to the library

> Please fill out the table below with the desired information per icon. This information must be included with the icon request before it can be accepted.

see the table below for a list of available categories

| category  | description |
|---|---|
|logo|Updated tail art for Ravn Air|
| alert     | Icons used specifically to alert users as to the state of awareness |
| in-flight | icons reserved for 'day of travel' user experiences |
| interface | Icons used to create interface enhancements |
| payment   | Icons specifically to be used in a transaction flow |
| shop      | icons for use with shopping experiences |
| social    | Icons for use with social media |
| terminal  | Icons related to terminal experiences |
| partnership  | Icons related to business partnerships and Alaska Airlines |
| logo  | Logo SVGs, e.g. tails or company logos |

- **Name:** What is the name of the icon? Please update the name of the file to match.
- **Category:** What category of icons will this new icon be listed?
- **Title:** An OPTIONAL description of the icon. ††
- **Description:** Alternative text of the icon that will be read back to assistive technologies.

<small>†† The title is only needed if there is text that you wish to appear in the native browser tooltip functionality. See an example with the [external link](https://auro.alaskaair.com/icons) icon in the **interface** section.</small>

| name | category | title | description |
|---|---|---|---|
|tail-7H|logo|Ravn Alaska Tail|Ravn Alaska tail with logo|

## Icon art

> The icon(s) per this request, has the new art been completed?

- [x] Yes
- [ ] No

> If YES, does the new icon art follow all the recommendations from the [Auro Icon Design Guidelines](https://auro.alaskaair.com/foundations/iconography/design-guidelines)?

- [x] Yes
- [ ] No
![Ravn_Update_Final](https://user-images.githubusercontent.com/83242595/215651624-4427f86b-ea19-4fc7-ae6b-b1c0783a715c.png)

> If YES, the icon(s) in the request, have they been added to the UiKit Abstract repo?

- [x] Yes
- [ ] No

### Attach exported SVG files to this issue

See the options below for attaching a file to this request.
![Ravn_Update_Final](https://user-images.githubusercontent.com/83242595/215651645-b36fc0cb-ccb2-493e-9c7a-ad8991a19c60.png)

**Comment by KaylaBlyton1** [comment]
@blackfalcon - apologies, I broke your table and can't figure out how to fix it. Lmk if I can clarify any information

**Comment by Sandeepchidipudi** [comment]
@blackfalcon  can you please help us to raise a PR for this issue and get this merged

**Comment by gusnaughton** [comment]
@jason-capsule42 the file was submitted as tail-RA.svg, RA is Royal Nepal AIrlines. The correct IATA code is 7H. This should be resubmitted with a new filename.
