### ISSUE TITLE
Figma stickersheet

### ISSUE THREAD

**Issue by leeejune** [AlaskaAirlines/Icons#191]
## Is your feature request related to a problem? Please describe.

We are working to sync between the ITS and Auro icon set. There is lack of documentation for icons and an opportunity to add icon guidelines.

## Describe the solution you'd like

Revamp the current icon stickersheet in Figma.

## Links
[Current icon file](https://www.figma.com/file/lZwTWQqadBc84DJcZ26RU7/Auro-Icons?node-id=0%3A1)
[Working file](https://www.figma.com/file/xTecLouGq4CdJRrASQj0wj/revamp-stickersheet?node-id=0-1)

**Comment by blackfalcon** [comment]
@leeejune is there any followup to this? Are there any changed that need to happen for Auro to support ITS icons?
