### ISSUE TITLE
Filled & un-filled icons

### ISSUE THREAD

**Issue by EricGalindo1** [AlaskaAirlines/Icons#210]
# Add new icon(s) to the library

> Please fill out the table below with the desired information per icon. This information must be included with the icon request before it can be accepted.

see the table below for a list of available categories

| category  | description |
|-----------|-------------|
| alert     | Icons used specifically to alert users as to the state of awareness |
| in-flight | icons reserved for 'day of travel' user experiences |
| interface | Icons used to create interface enhancements |
| payment   | Icons specifically to be used in a transaction flow |
| shop      | icons for use with shopping experiences |
| social    | Icons for use with social media |
| terminal  | Icons related to terminal experiences |
| partnership | Icons related to business partnerships |
| programs | Icons related to Alaska Airlines programs |
| logo  | Logo SVGs, e.g. tails or company logos |

- **Name:** What is the name of the icon? Please update the name of the file to match. PLEASE reference other similar icons for a naming convention.
- **Category:** What category of icons will this new icon be listed?
- **Title:** An OPTIONAL description of the icon. ††
- **Description:** Alternative text of the icon that will be read back to the user via assistive technologies.

<small>†† The title is only needed if there is text that you wish to appear in the native browser tooltip functionality. See an example with the [external link](https://auro.alaskaair.com/icons) icon in the **interface** section.</small>

| name | category | accessibility description |
|---|---|---|
| error-filled | alert | triangle with exclamation mark |
| rising-sun-stroke | destination | semi-circle with lines |
| sun-stroke | destination | full circle surrounded with lines |
| hotel-filled | destination | two rectangles with windows |
| contract-mixed-fare-filled | easybiz | two gold rectangles with a white stroke in the middle |
| contract-fare-filled | easybiz | two blue rectangles with a white dollar symbol in the middle |
| flight-pass-filled | easybiz | rectangle with airplane in the middle and three circles on top |
| government-fare-stroke | easybiz | blue dome building |
| government-mixed-fare-stroke | easybiz | yellow dome building |
| mask-filled | health | face mask |
| medical-filled | health | circle with a cross in the middle |
| clean-filled | health | sanitizing spray |
| covid-test-filled | health | test tube |
| carry-on-filled | in-flight | backpack with front zipper |
| entertainment-filled | in-flight | a rectangle with triangle inside |
| luggage-filled | in-flight | a rectangle with wheels and handle |
| plug-filled | in-flight | rectangle with two lines |
| seat-filled | in-flight | airline seat |
| wine-and-spirits-filled | in-flight | wine glass |
| passenger-filled | in-flight | circle with a single passenger outline |
| multipax-filled | in-flight | circle with two passengers |
| search-filled | interface | magnifying glass with dark circle in the middle |
| chat-filled | interface | two rectangle chat bubble |
| new-window-filled | interface | two rectangle with plus sign |
| filter-filled | interface | marker sign |
| location-found-stroke | interface | target circle with a dot in the center |
| notification-filled | interface | a bell |
| notification-active-filled | interface | a bell with red dot |
| view-password-filled | interface | eye |
| tag-stroke | interface | bag tag |
| pin-trip-stroke | interface | drop pin with circles |
| phone-filled | interface | rectangle phone |
| settings-filled | interface | a cog gear |
| id-filled | interface | rectangle with id silhouette inside  |
| hide-password-filled | interface | eye with a line in the middle |
| printer-filled | interface | a printer |
| add-to-calendar-filled | interface | rectangle calendar with a plus sign |
| calendar-filled | interface | rectangular calendar |
| route-pending-government-approval-stroke | interface-sell | dome building |
| discount-code-applied-stroke | interface-sell | green clover with a checkmark |
| first-class-upgrade-available-filled | interface-sell | ribbon with a letter "F" |
| first-class-upgrade-waitlist-filled| interface-sell | a clock ribbon |
| premium-class-upgrade-available-filled | interface-sell | purple start with a letter "P"|
| premium-class-upgrade-waitlist-filled | interface-sell | gold start with watch face |
| recommended-for-standby-filled | interface-sell | green smiley face |
| recommended-for-standby-travel-but-watch-filled | interface-sell | yellow neutral face |
| not-recommended-for-standby-filled | interface-sell | red frown face |
| shopping-bag-filled | shop | shopping bag with a handle |
| cart-filled | shop | a shopping cart |
| credit-card-filled | shop | credit card |
| receipt-filled | shop | receipt paper |
| gift-filled | shop | gift box with a bow |

## Icon art

> The icon(s) per this request, has the new art been completed?

- [x] Yes
- [ ] No

> If YES, does the new icon art follow all the recommendations from the [Auro Icon Design Guidelines](https://auro.alaskaair.com/foundations/iconography/design-guidelines)?

- [x] Yes
- [ ] No

> If YES, the icon(s) in the request, have they been added to the UiKit Abstract repo?

- [x] Yes
- [ ] No

### Attach exported SVG files to this issue
[alert:error-filled.svg.zip](https://github.com/AlaskaAirlines/Icons/files/12217253/alert.error-filled.svg.zip)
[destination:rising-sun-stroke.svg.zip](https://github.com/AlaskaAirlines/Icons/files/12222171/destination.rising-sun-stroke.svg.zip)
[destination:sun-stroke.svg.zip](https://github.com/AlaskaAirlines/Icons/files/12222176/destination.sun-stroke.svg.zip)
[destination:hotel-filled.svg.zip](https://github.com/AlaskaAirlines/Icons/files/12222199/destination.hotel-filled.svg.zip)
[easybiz:contract-mixed-fare-filled.svg.zip](https://github.com/AlaskaAirlines/Icons/files/12222346/easybiz.contract-mixed-fare-filled.svg.zip)
[easybiz:contract-fare-filled.svg.zip](https://github.com/AlaskaAirlines/Icons/files/12222467/easybiz.contract-fare-filled.svg.zip)
[easybiz:flight-pass-filled.svg.zip](https://github.com/AlaskaAirlines/Icons/files/12222498/easybiz.flight-pass-filled.svg.zip)
[easybiz:government-fare-stroke.svg.zip](https://github.com/AlaskaAirlines/Icons/files/12222511/easybiz.government-fare-stroke.svg.zip)
[easybiz:government-mixed-fare-stroke.svg.zip](https://github.com/AlaskaAirlines/Icons/files/12591185/easybiz.government-mixed-fare-stroke.svg.zip)
[health:medical-filled.svg.zip](https://github.com/AlaskaAirlines/Icons/files/12255191/health.medical-filled.svg.zip)
[health:mask-filled.svg.zip](https://github.com/AlaskaAirlines/Icons/files/12255193/health.mask-filled.svg.zip)
[health:clean-filled.svg.zip](https://github.com/AlaskaAirlines/Icons/files/12253279/health.clean-filled.svg.zip)
[covid-test-filled.svg.zip](https://github.com/AlaskaAirlines/Icons/files/13385276/covid-test-filled.svg.zip)
[in-flight:carry-on-filled.svg.zip](https://github.com/AlaskaAirlines/Icons/files/12264765/in-flight.carry-on-filled.svg.zip)
[in-flight:entertainment-filled.svg.zip](https://github.com/AlaskaAirlines/Icons/files/12264868/in-flight.entertainment-filled.svg.zip)
[in-flight:luggage-filled.svg.zip](https://github.com/AlaskaAirlines/Icons/files/12264872/in-flight.luggage-filled.svg.zip)
[in-flight:plug-filled.svg.zip](https://github.com/AlaskaAirlines/Icons/files/12264959/in-flight.plug-filled.svg.zip)
[in-flight:seat-filled.svg.zip](https://github.com/AlaskaAirlines/Icons/files/12282820/in-flight.seat-filled.svg.zip)
[in-flight:wine-and-spirits-filled.svg.zip](https://github.com/AlaskaAirlines/Icons/files/12282932/in-flight.wine-and-spirits-filled.svg.zip)
[in-flight:passenger-filled.svg.zip](https://github.com/AlaskaAirlines/Icons/files/12315323/in-flight.passenger-filled.svg.zip)
[in-flight:multipax-filled.svg.zip](https://github.com/AlaskaAirlines/Icons/files/12371611/in-flight.multipax-filled.svg.zip)
[interface:search-filled.svg.zip](https://github.com/AlaskaAirlines/Icons/files/12526421/interface.search-filled.svg.zip)
[interface:new-window-filled.svg.zip](https://github.com/AlaskaAirlines/Icons/files/12526579/interface.new-window-filled.svg.zip)
[interface:filter-filled.svg.zip](https://github.com/AlaskaAirlines/Icons/files/12527391/interface.filter-filled.svg.zip)
[interface:location-found-stroke.svg.zip](https://github.com/AlaskaAirlines/Icons/files/12527399/interface.location-found-stroke.svg.zip)
[interface:notification-filled.svg.zip](https://github.com/AlaskaAirlines/Icons/files/12528595/interface.notification-filled.svg.zip)
[interface:notification-active-filled.svg.zip](https://github.com/AlaskaAirlines/Icons/files/12528615/interface.notification-active-filled.svg.zip)
[interface:view-password-filled.svg.zip](https://github.com/AlaskaAirlines/Icons/files/12528629/interface.view-password-filled.svg.zip)
[interface:tag-stroke.svg.zip](https://github.com/AlaskaAirlines/Icons/files/12528673/interface.tag-stroke.svg.zip)
[interface:pin-trip-stroke.svg.zip](https://github.com/AlaskaAirlines/Icons/files/12590406/interface.pin-trip-stroke.svg.zip)
[interface:phone-filled.svg.zip](https://github.com/AlaskaAirlines/Icons/files/12590469/interface.phone-filled.svg.zip)
[interface:settings-filled.svg.zip](https://github.com/AlaskaAirlines/Icons/files/12590481/interface.settings-filled.svg.zip)
[interface:id-filled.svg.zip](https://github.com/AlaskaAirlines/Icons/files/12590513/interface.id-filled.svg.zip)
[interface:hide-password-filled.svg.zip](https://github.com/AlaskaAirlines/Icons/files/12590585/interface.hide-password-filled.svg.zip)
[interface:printer-filled.svg.zip](https://github.com/AlaskaAirlines/Icons/files/12590603/interface.printer-filled.svg.zip)
[interface:add-to-calendar-filled.svg.zip](https://github.com/AlaskaAirlines/Icons/files/12590850/interface.add-to-calendar-filled.svg.zip)
[interface:calendar-filled.svg.zip](https://github.com/AlaskaAirlines/Icons/files/12590851/interface.calendar-filled.svg.zip)
[interface:sell:route-pending-government-approval-stroke.svg.zip](https://github.com/AlaskaAirlines/Icons/files/12591038/interface.sell.route-pending-government-approval-stroke.svg.zip)
[interface:sell:discount-code-applied-stroke.svg.zip](https://github.com/AlaskaAirlines/Icons/files/12591056/interface.sell.discount-code-applied-stroke.svg.zip)
[interface:sell:first-class-upgrade-available-filled.svg.zip](https://github.com/AlaskaAirlines/Icons/files/12591089/interface.sell.first-class-upgrade-available-filled.svg.zip)
[interface:sellfirst-class-upgrade-waitlist-stroke.svg.zip](https://github.com/AlaskaAirlines/Icons/files/12591103/interface.sellfirst-class-upgrade-waitlist-stroke.svg.zip)
[interface:sell:premium-class-upgrade-available-filled.svg.zip](https://github.com/AlaskaAirlines/Icons/files/12591127/interface.sell.premium-class-upgrade-available-filled.svg.zip)
[interface:sell:premium-class-upgrade-waitlist-filled.svg.zip](https://github.com/AlaskaAirlines/Icons/files/12591160/interface.sell.premium-class-upgrade-waitlist-filled.svg.zip)
[interface:sell:premium-class-upgrade-waitlist-filled.svg.zip](https://github.com/AlaskaAirlines/Icons/files/12591203/interface.sell.premium-class-upgrade-waitlist-filled.svg.zip)
[interface:sell:recommended-for-standby-filled.svg.zip](https://github.com/AlaskaAirlines/Icons/files/12591328/interface.sell.recommended-for-standby-filled.svg.zip)
[interface:sell:recommended-for-standby-travel-but-watch-filled.svg.zip](https://github.com/AlaskaAirlines/Icons/files/12591263/interface.sell.recommended-for-standby-travel-but-watch-filled.svg.zip)
[interface:sell:not-recommended-for-standby-filled.svg.zip](https://github.com/AlaskaAirlines/Icons/files/12591305/interface.sell.not-recommended-for-standby-filled.svg.zip)
[shop:shopping-bag-filled.svg.zip](https://github.com/AlaskaAirlines/Icons/files/12612302/shop.shopping-bag-filled.svg.zip)
[shop:cart-filled.svg.zip](https://github.com/AlaskaAirlines/Icons/files/12612309/shop.cart-filled.svg.zip)
[shop:credit-card-filled.svg.zip](https://github.com/AlaskaAirlines/Icons/files/12612316/shop.credit-card-filled.svg.zip)
[shop:receipt-filled.svg.zip](https://github.com/AlaskaAirlines/Icons/files/12612344/shop.receipt-filled.svg.zip)
[shop:gift-filled.svg.zip](https://github.com/AlaskaAirlines/Icons/files/12612354/shop.gift-filled.svg.zip)
[chat-filled.svg.zip](https://github.com/AlaskaAirlines/Icons/files/13395386/chat-filled.svg.zip)

DO NOT upload the icon(s) directly. ALWAYS compress the file(s) and upload the `.zip` file.

See the options below for attaching a file to this request.

**Comment by leeejune** [comment]
![covid-test-filled](https://github.com/AlaskaAirlines/Icons/assets/55998746/728c9805-5327-4720-a743-d3aabcea5a19)

@jordanjones243

**Comment by Patrick-Daly-AA** [comment]
We will be returning to this work once we have implemented the icon deprecation procedure, since it is necessary for completing this work.  The one exception is for the "rising-sun-stroke" icon, as we will be adding that shortly.

**Comment by blackfalcon** [comment]
1. First pass at renaming all the icons to meet the spec of either `stroke` or `filled` for each icon. Design support will be needed as not all icons fit nicely onto these categories. For example, `arrow-up`, `chain-link` or `air`. 
1. Reviewing some of the new icons there is an issue where the asset is not a shape, but fills on lines. All the icons need to be a single shape that is mono-colored. 
1. There appears to be a mix of icons that already exist and new ones. Please only upload the icons that are new. 
1. Please add all the icons to a single folder and .ZIP that into a single download. 
1. Please do not include the path name into the name of the icon. Place the icons into different category folders.

**Comment by yvonneyamasaki** [comment]
@blackfalcon @leeejune 

Here are the icons referenced in this ticket. Please let me know if they arent named correctly and i missed an icon. 
[Icons.zip](https://github.com/AlaskaAirlines/Icons/files/14366576/Icons.zip)
