### ISSUE TITLE
New Bahamasair tail logo

### ISSUE THREAD

**Issue by michelle-alaskaair** [AlaskaAirlines/Icons#215]
### Icon attributes

name | category | accessibility description
-- | -- | --
Bahamasair Tail | Tail Art | White airplane tail with colorful Bahamasair logo

### The icon(s) per this request, has the new art been completed?

Yes, art has been added to the Figma docs

### Attach exported SVG files to this issue

[Bahamasair_Final.svg.zip](https://github.com/AlaskaAirlines/Icons/files/12862861/Bahamasair_Final.svg.zip)

**Comment by Sandeepchidipudi** [comment]
hello @leeejune  can you please make a PR for this issue as this logo needs to be prod by tomorrow
