### ISSUE TITLE
icons: Implement Icon Deprecation indication

### ISSUE THREAD

**Issue by Patrick-Daly-AA** [AlaskaAirlines/Icons#224]
### Is your feature request related to a problem? Please describe.

As an Auro Contributor
I want to have a clear indicator as to whether an icon is deprecated or not
so that I can clearly communicate to Auro Users which Icons they should use

### Describe the solution you'd like

Initial early idea is to use some sort of HTML or Data flag to indicate an icon is deprecated within the JSON file.

### Additional context

#210 Is what has spurred us to take on this improvement

### Exit criteria

I know I'm done when:

- Icons can be indicated in some way as being deprecated
- Icons are also indicated as deprecated in Figma Documentation

**Comment by jordanjones243** [comment]
I haven't looked too much into this, but it seems like there may be a deprecation strategy already in place. This will need some more investigation.

![Image](https://github.com/AlaskaAirlines/Icons/assets/55807669/2053a552-5f18-4c40-8882-7449e3acc590)
![Image](https://github.com/AlaskaAirlines/Icons/assets/55807669/98b2cc6d-555a-4309-9498-5b5e1bef5771)
