### ISSUE TITLE
new pin icons

### ISSUE THREAD

**Issue by Julieta253** [AlaskaAirlines/Icons#240]
### New pin icons

| pin-filled | interface | pin filled in | A pin pointing downwards filled in |

| pin-stroke | interface | pin outlined | A pin pointing downwards outlined |

### The icon(s) per this request, has the new art been completed?

Yes, art has been added to the Figma docs

### Attach exported SVG files to this issue

[interface:pin-filled.svg.zip](https://github.com/AlaskaAirlines/Icons/files/14560715/interface.pin-filled.svg.zip)
[interface:pin-stroke.svg.zip](https://github.com/AlaskaAirlines/Icons/files/14560716/interface.pin-stroke.svg.zip)

**Comment by blackfalcon** [comment]
@Julieta253 Please see issue https://github.com/AlaskaAirlines/Icons/issues/210

With direction from @EricGalindo1 we implemented a series of updates, some of those updates are related to how icons are described. 

I am curious what the design team is considering the standard. Your icon descriptions are describing the action the icon represents and the updates we made, as will see, are more descriptive of the appearance of the icon. 

Please reach out if you have any questions.

**Comment by Julieta253** [comment]
Hello @blackfalcon I have edited the descriptions to match the new style. Let me know if there are any other issues to fix, thank you!
