### ISSUE TITLE
New Icons

### ISSUE THREAD

**Issue by nikogiani** [AlaskaAirlines/Icons#246]
### Icon attributes

1. explore-fill | light | explore fill | Icon for app navigation bar for explore page
2. explore-stroke | light | explore stroke | Icon for app navigation bar for explore page
3. book-fill | light | book fill | Icon for app navigation bar for book page
4. book-stroke | light | book stroke | Icon for app navigation bar for book page
5. trips-fill | light | trips fill | Icon for app navigation bar for trips page
6. trips-stroke | light | trips stroke | Icon for app navigation bar for trips page
7. account-fill | light | account fill | Icon for app navigation bar for account page
8. account-stroke | light | account stroke | Icon for app navigation bar for account page
9. more-fill | light | more fill | Icon for app navigation bar for more page
10. more-stroke | light | more stroke | Icon for app navigation bar for more page

### The icon(s) per this request, has the new art been completed?

- [x] Yes
- [ ] No

### Attach exported SVG files to this issue

[account-fill.svg.zip](https://github.com/AlaskaAirlines/Icons/files/14938762/account-fill.svg.zip)
[account-stroke.svg.zip](https://github.com/AlaskaAirlines/Icons/files/14938763/account-stroke.svg.zip)
[book-fill.svg.zip](https://github.com/AlaskaAirlines/Icons/files/14938764/book-fill.svg.zip)
[book-stroke.svg.zip](https://github.com/AlaskaAirlines/Icons/files/14938765/book-stroke.svg.zip)
[explore-fill.svg.zip](https://github.com/AlaskaAirlines/Icons/files/14938766/explore-fill.svg.zip)
[explore-stroke.svg.zip](https://github.com/AlaskaAirlines/Icons/files/14938768/explore-stroke.svg.zip)
[more-fill.svg.zip](https://github.com/AlaskaAirlines/Icons/files/14938769/more-fill.svg.zip)
[more-stroke.svg.zip](https://github.com/AlaskaAirlines/Icons/files/14938772/more-stroke.svg.zip)
[trips-fill.svg.zip](https://github.com/AlaskaAirlines/Icons/files/14938773/trips-fill.svg.zip)
[trips-stroke.svg.zip](https://github.com/AlaskaAirlines/Icons/files/14938774/trips-stroke.svg.zip)

**Comment by michelle-alaskaair** [comment]
@Patrick-Daly-AA I have requested design updates to these icons. @nikogiani Let me know if you have questions about my comments in Figma and tag me when the updated icons are ready to review. Once approved, you can attach new svgs to this issue. Thanks!

**Comment by michelle-alaskaair** [comment]
Closing the issue since we decided not to add the Excursion nav icons to our library. For now, they will host them separately.

**Comment by michelle-alaskaair** [comment]
Closing the issue since we decided not to add the Excursion nav icons to our library. For now, they will host them separately.
