### ISSUE TITLE
New destination icons for Google NLS experience

### ISSUE THREAD

**Issue by Julieta253** [AlaskaAirlines/Icons#256]
### Icon attributes

| flag-stroke | destination | An outlined flag
| mountain-stroke | destination | Two outlined mountains and a sun
| snowflake-stroke | destination | An outlined snowflake
| sun-stroke | destination | An outlined sun

### The icon(s) per this request, has the new art been completed?

Yes, art has been added to the Figma docs

### Attach exported SVG files to this issue

[destination.zip](https://github.com/user-attachments/files/16194935/destination.zip)

**Comment by blackfalcon** [comment]
PR was merged and icons were released. Added to this PR for Auro Doc Site https://github.com/AlaskaAirlines/AuroDocsSite/pull/226/commits/8b971bd86e21e38d45aa020aa7fc08ebe53ffa4d
