### ISSUE TITLE
Food and drink icon

### ISSUE THREAD

**Issue by sryckman** [AlaskaAirlines/Icons#30]
# Add new icon(s) to the library

> Please list the icon(s) that need to be added to the library

1. food and drink

## Icon art

> The icon(s) per this request, has the new art been completed?

- [x] Yes
- [ ] No

> If YES, does the new icon art follow all the recommendations from the [Auro Icon Design Guidlines](https://auro.alaskaair.com/foundations/iconography/design-guidelines)?

- [x] Yes

- [ ] No

> If YES, the icon(s) in the request, have they been added to the UiKit Abstract repo?

- [x] Yes
- [ ] No

### Attach exported SVG files to this issue
[food-and-drink.svg.zip](https://github.com/AlaskaAirlines/OrionIcons/files/4440736/food-and-drink.svg.zip)

See the options below for attaching a file to this request.

**Comment by blackfalcon** [comment]
in-flight category
