### ISSUE TITLE
Airline Logos

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/Icons#37]
# Add new icon(s) to the library

> Please fill out the table below with the desired information per icon

In order to serve many of the dev teams, a new section for Airline Logos in SVG format is requested. 

## Icon art

> The icon(s) per this request, has the new art been completed?

- [X] Yes
- [ ] No

> If YES, does the new icon art follow all the recommendations from the [Auro Icon Design Guidelines](https://auro.alaskaair.com/foundations/iconography/design-guidelines)?

- [ ] Yes
- [X] No

These are logos provided by individual airlines. Post this update we will look at optimizing to the Auro standard.

**Comment by gusnaughton** [comment]
Something I didn't mention before is for accessibility support, we need to add a 
```<title></title>``` as a child of ```<svg>```. I can add this once you push your branch.

**Comment by blackfalcon** [comment]
@gusnaughton the processed SVGs from this lib address a11y, here is an example

```
<svg viewBox="0 0 50.329418 24.648584" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" role="img" aria-hidden="true" style="width: 100%; height: auto; fill: currentColor" class="" >
  <title>Ravn Alaska</title>
  <desc>Logo image for Ravn Alaska</desc>
```
