### ISSUE TITLE
Lap Infant Icon

### ISSUE THREAD

**Issue by erikalanghauser** [AlaskaAirlines/Icons#43]
# Add new icon(s) to the library
| name | category | description |
| lap infant | interface | icon to enhance the interface by indicating a lap infant or lap infant-related information |

## Icon art
Here is an example of a previously created lap infant icon that was recommended for Orion, but never officially approved or added to the icon library. Something like this would work for our lap infant needs.
![image](https://user-images.githubusercontent.com/34354487/95617193-e1978680-0a1f-11eb-9b49-ca99ee2afb18.png)

> The icon(s) per this request, has the new art been completed?

- [ ] Yes
- [X] No

> If YES, does the new icon art follow all the recommendations from the [Auro Icon Design Guidelines](https://auro.alaskaair.com/foundations/iconography/design-guidelines)?

- [ ] Yes
- [ ] No

> If YES, the icon(s) in the request, have they been added to the UiKit Abstract repo?

- [ ] Yes
- [ ] No

### Attach exported SVG files to this issue

See the options below for attaching a file to this request.

**Comment by blackfalcon** [comment]
@erikalanghauser can you export the SVG from Sketch and attach it to this issue? Thanks!

**Comment by blackfalcon** [comment]
@erikalanghauser what is the status of this icon?

**Comment by erikalanghauser** [comment]
Here is the compressed svg.
[lap-infant.svg.zip](https://github.com/AlaskaAirlines/Icons/files/5778717/lap-infant.svg.zip)

**Comment by blackfalcon** [comment]
@erikalanghauser can I get a new export of this icon. The SVG here is cut to `0 0 13 18`, and the [standard set](https://auro.alaskaair.com/icons/overview) specifies `0 0 25 25`. 

If there are issues with this, please consult with @sryckman 

Here is a screen shot of how this doesn't fit the preferred layout grid. 

<img width="361" alt="Screen Shot 2021-01-06 at 9 16 00 PM" src="https://user-images.githubusercontent.com/181089/103854091-7ed87a00-5064-11eb-8e02-8084ba4be32e.png">

**Comment by erikalanghauser** [comment]
Uploading new SVG meeting Auro guidelines with Suze's tweaks.

[lap-infant.svg.zip](https://github.com/AlaskaAirlines/Icons/files/5908029/lap-infant.svg.zip)

**Comment by blackfalcon** [comment]
Updated to correct version

<img width="150" alt="Screen Shot 2021-02-10 at 7 27 27 PM" src="https://user-images.githubusercontent.com/181089/107599699-3ae21300-6bd6-11eb-9e5b-2fe924871037.png">
