### ISSUE TITLE
New icons for inflight amenities

### ISSUE THREAD

**Issue by clockeby** [AlaskaAirlines/Icons#45]
## Is your feature request related to a problem? Please describe.
We'd like the seat map to better market inflight experience upgrades to guests in a way that is easily scannable when scrolling through the full plane layout. Many amenities are already well represented by Auro inflight icons but could be improved by adding new icons to capture key differences in the experiences.

## Describe the solution you'd like
1. Complementary cocktails icon: (Premium Class) Currently food and drink are only represented by the "meal service" icon (fork & spoon) which is only applicable to First Class. Using the same icon to represent complementary cocktails for Premium Class does not do enough to differentiate the two while scanning the seat map.
2. More legroom icon: (Premium Class) Currently there is only one "seat" icon which is used in many contexts such as referencing comfort and seat selection for fare comparison and safety for seat blocking. For communicating the additional legroom available with Premium Class seats at a glance, an icon designed for this purpose would be helpful.
3. Most legroom icon: (First Class) As mentioned in AlaskaAirlines/auro-icon#2 above, the only seat icon currently available is not specific to the use case of communicating the comfort and legroom available in First Class. Ideally, this icon and the More legroom icon would be slightly similar so as to communicate increasing levels of the same benefit.

## Describe alternatives you've considered
Due to the nature of these inflight features the iconography would need to be fairly specific to the use cases provided above. Keeping the icons tied to the Auro family in style would also make them easy to use in other marketing contexts beyond the seat map.

## Additional context
These are placeholder icons from a previous design system iteration provided by UI Design.
![image](https://user-images.githubusercontent.com/9092702/95913535-3e18df80-0d59-11eb-8258-1787f8a3cd36.png)

**Comment by sryckman** [comment]
@clockeby Are the placeholder icons from a specific location (noun project, other airline app)? Would like to know to avoid a scenario where I rip off their style vs exploring something with more differentiation.

@blackfalcon where on this page do I find info about when these are needed by?

**Comment by blackfalcon** [comment]
@sryckman I have no information on any deadline or expectation. What I have is in this ticket.

**Comment by clockeby** [comment]
@sryckman I've updated the mockup to use the placeholder icons you provided. I was able to edit them to match the existing Auro icons in size and stroke weight.

**Comment by blackfalcon** [comment]
@sryckman and @clockeby what is the request here? Are there new icons coming to be added to the lib or is this issues closed?

**Comment by clockeby** [comment]
Correct on the first part, the request is to add new icons to the library.

**Comment by blackfalcon** [comment]
If there are new icons to be added, please ... 

1. add them to the UI Kit
1. Export correct size SVGs
1. Attach to this issue to be included or submit a PR with the added icons to the lib

@sryckman @clockeby

**Comment by clockeby** [comment]
Update: I've added the icons to a new branch in the UI Kit. I'm awaiting a review with Vidal and/or Suzanne. Once the UI Kit versions are approved I'll export the SVGs.

**Comment by blackfalcon** [comment]
@clockeby or @sryckman what is the status of this work? Are there icons to add or ... ?

**Comment by blackfalcon** [comment]
Status moved to BLOCKED as there have been no updates on design requests for 11 days.

**Comment by clockeby** [comment]
Thanks for the reminder! I've been occupied with porting assets info Figma. I'll at the SVGs and submit a pull request.

**Comment by sryckman** [comment]
@clockeby Are they all in here?:
https://www.figma.com/file/lZwTWQqadBc84DJcZ26RU7/Auro-icons?node-id=0%3A1

**Comment by clockeby** [comment]
They are. They've been added to both libraries.

**Comment by sryckman** [comment]
Sweet, thanks! Sorry for the question, I couldn't spot the wine glass at first :D

**Comment by clockeby** [comment]
No worries!
