### ISSUE TITLE
auro-avatar: airline code incorrect for Finnair tail

### ISSUE THREAD

**Issue by Eliza-Huang** [AlaskaAirlines/Icons#65]
## Describe the bug
tail-FI.svg should be renamed to tail-AY.svg since the airline code for Finnair is AY (Icelandair has the airline code FI).

## To Reproduce
1. Click on the tail-FI.svg file to see the Finnair tail

## Expected behavior
tail-AY.svg should contain the Finnair tail.

**Comment by blackfalcon** [comment]
Issues resolved.

<img width="259" alt="Screen Shot 2021-02-07 at 10 31 21 PM" src="https://user-images.githubusercontent.com/181089/107183784-40501b00-6994-11eb-8b46-c48fd90a251e.png">
