### ISSUE TITLE
Delta Tail Logo

### ISSUE THREAD

**Issue by gusnaughton** [AlaskaAirlines/Icons#66]
# Add new icon(s) to the library

> Please fill out the table below with the desired information per icon

| name | category | description |
|---|---|---|
| tail-DL | logo | Delta Air Lines |

## Icon art

> The icon(s) per this request, has the new art been completed?

- [x] Yes
- [ ] No

> If YES, does the new icon art follow all the recommendations from the [Auro Icon Design Guidelines](https://auro.alaskaair.com/foundations/iconography/design-guidelines)?

- [x] Yes
- [ ] No

> If YES, the icon(s) in the request, have they been added to the UiKit Abstract repo?

- [ ] Yes
- [ ] No

### Attach exported SVG files to this issue

See the options below for attaching a file to this request.

**Comment by gusnaughton** [comment]
@vidalmenAS  has this been added to the UIKit?

**Comment by gusnaughton** [comment]
[DELTA.svg.zip](https://github.com/AlaskaAirlines/Icons/files/6064388/DELTA.svg.zip)

**Comment by vidalmenAS** [comment]
@gusnaughton no (at least not yet) - this hasn't been approved yet for widespread usage beyond a couple of exceptions including flight details but when there is more definition we may add.

**Comment by blackfalcon** [comment]
I’m confused as to the state of things. Can this tail be added to the lib?

**Comment by vidalmenAS** [comment]
@blackfalcon lib is fine my comment to gus was only about the UI Kit on figma. We've not added any tails as symbols yet on the design side.
