### ISSUE TITLE
Health and Destination Icons

### ISSUE THREAD

**Issue by KyleJones2** [AlaskaAirlines/Icons#82]
# Add new icon(s) to the library

**Name**: Sun, Hotel, Mask, Covid Test, Air, Health, Spray Bottle
**Category**: Destination and Health
**Description**: The Sun and Hotel icon are for destinations, while the Mask, Covid Test, Air, Health, and Spray Bottle are for the new Health section. 

## Icon art

> The icon(s) per this request, has the new art been completed?

- [X] Yes
- [ ] No

> If YES, does the new icon art follow all the recommendations from the [Auro Icon Design Guidelines](https://auro.alaskaair.com/foundations/iconography/design-guidelines)?

- [X] Yes
- [ ] No

> If YES, the icon(s) in the request, have they been added to the UiKit Abstract repo?

- [X] Yes
- [ ] No

### Attach exported SVG files to this issue

See the options below for attaching a file to this request.

[Icon.zip](https://github.com/AlaskaAirlines/Icons/files/6407202/Icon.zip)

**Comment by blackfalcon** [comment]
@KyleJones2 added the new icons. In the description you reference a `spray bottle`. This was NOT in the zip folder you attached. 

Also, I need a description per icon please, for a11y. Thanks! 

![Screen Shot 2021-06-18 at 10 32 27 AM](https://user-images.githubusercontent.com/181089/122598066-2cdb4d80-d021-11eb-804f-84006bc4b07d.png)

**Comment by KyleJones2** [comment]
[Health.zip](https://github.com/AlaskaAirlines/Icons/files/6689128/Health.zip)

@blackfalcon Attached is the Spray Bottle, thank you for flagging that. 

What kind of description is needed for each icon?

**Comment by blackfalcon** [comment]
Added. Just need all the icon descriptions. 

![Screen Shot 2021-06-21 at 1 07 30 PM](https://user-images.githubusercontent.com/181089/122821622-f0625880-d291-11eb-959a-86c0b5f7232d.png)
