### ISSUE TITLE
food and drink icon should not have fill

### ISSUE THREAD

**Issue by sryckman** [AlaskaAirlines/Icons#85]
Auro docsite shows food and drink icon with filled spoon; developed work also shows fill. Icon should be stroke only, no fill on spoon.

Please pull SVG from this file:
https://www.figma.com/file/lZwTWQqadBc84DJcZ26RU7/Auro-Icons?node-id=7%3A22

**Comment by blackfalcon** [comment]
@sryckman 

![Screen Shot 2021-06-02 at 11 35 20 AM](https://user-images.githubusercontent.com/181089/120534395-9f4bfc80-c396-11eb-8b0a-9488999260ba.png)

If an exported SVG could be attached to this issue, that would be greatly appreciated.

**Comment by blackfalcon** [comment]
@sryckman can you please export the SVG and attach to this issue? I struggled to do this correctly and need help. -- thanks!

**Comment by leeejune** [comment]
@blackfalcon Github doesn't support a svg file so I will send on teams.

**Comment by blackfalcon** [comment]
> @blackfalcon Github doesn't support a svg file so I will send on teams.

Correct. It will work if you attach a ZIP file.

**Comment by blackfalcon** [comment]
Icon has been updated and released. See update in the Auro doc site.
