### ISSUE TITLE
Update categorization of new Interface icons

### ISSUE THREAD

**Issue by KaylaBlyton1** [AlaskaAirlines/Icons#91]
# General Support Request

## Support request

A portion of icons (listed in the next section below) have been updated in Figma components to be in a sub-category under Interface, called "Interface/Sell". This means that the categorization is now different between designers and developers.

## Possible Solution

Recategorize the icons for developers to match the new labeling:

Interface/Sell/route-pending-government-approval
Interface/Sell/mixed-cabin-itinerary
Interface/Sell/discount-code-applied
Interface/Sell/free-same-day-change
Interface/Sell/first-class-upgrade-available 
Interface/Sell/first-class-upgrade-waitlist
Interface/Sell/premium-class-upgrade-available 
Interface/Sell/premium-class-upgrade-waitlist
Interface/Sell/recommended-for-standby
Interface/Sell/recommended-for-standby-travel-but-watch
Interface/Sell/not-recommended-for-standby

## Context

The reason for this update is because most interface icons are not specific to the Sell experience. They are more generic UI icons. Putting these new icons in a subcategory will allow for quicker access - less sifting to source the correct icon. 

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project: https://www.figma.com/file/lZwTWQqadBc84DJcZ26RU7/Auro-Icons?node-id=616%3A22

**Comment by blackfalcon** [comment]
I see the reasoning behind the decision to sub-categorize, but I am hesitant to make this change in the Auro Icons repo as this sub-category maps too closely to a part of the business. 

**Interface** is a very broad stroke, I'd argue that there is a better opportunity to break up this large grouping into groups that are not mapped directly to parts of the business.

**Comment by KaylaBlyton1** [comment]
@blackfalcon - that is a good point (about breaking up Interface into smaller groups). To make sure I'm understanding, do you mean that the "Sell" name is too specific to the Sell team? In that case, I wonder if "shopping" or something similar would be best. 

There are two ways I could see Interface being segmented:
1. Interface remains as the umbrella category, with subcategories within it that hold the actual icons
2. Interface gets broken up into different categories, and the category of "Interface" ceases to exist

The way I'm thinking about it now, "Interface" is a category that could apply to all the icons on this screen and is not particularly descriptive. I think there is potential for sub-categories for icons, but option 2 above could be best for this specific instance (Interface ceases to exist, and a few more descriptive categories takes its place).

**Comment by blackfalcon** [comment]
I vote for a compromise. There are some icons in there that are pretty generic where `interface` makes sense. 

One thing that we need to be aware of, this will cause a BREAKING CHANGE as there is a dependency on the category when requesting an icon. Making this update will require users to update their references.

**Comment by KaylaBlyton1** [comment]
I'm on board with a compromise. :) 

When you say "Making this update will require users to update their references" - do you mean developers/designers who need to locate the icon? Or actual guests?

**Comment by blackfalcon** [comment]
> When you say "Making this update will require users to update their references" - do you mean developers/designers who need to locate the icon? Or actual guests?

Developers.

**Comment by KaylaBlyton1** [comment]
@blackfalcon - This convo fell off my radar, apologies. 

Got it, thank you for clarifying. We have made the update on the Figma side - lmk if I can help with this update any further.

**Comment by blackfalcon** [comment]
Can you provide a link to the updates in Figma? I am not sure what the engineering expectation is now.

**Comment by KaylaBlyton1** [comment]
Sure! Here is how we categorized it: https://www.figma.com/file/lZwTWQqadBc84DJcZ26RU7/Auro-Icons?node-id=0%3A1

**Comment by blackfalcon** [comment]
One thing we may consider that make this an easier transition. We can list an icon in multiple categories/sub-folders at the same time. 

So, this will allow us to deprecate the legacy location and move users to the new location and not cause a harsh breaking change. 

But, while I am open to a reorg, I am not a fan of creating a category that is directly tied to a part of the business, e.g. Sell. Is there a better category we can use?
