### ISSUE TITLE
Colored notification-active

### ISSUE THREAD

**Issue by arrenkhl** [AlaskaAirlines/Icons#92]
# Add new icon(s) to the library

> Please fill out the table below with the desired information per icon

| name | category | description |
|---|---|---|
|  notification-active  | interface | this icon is a colored version of the current notification-active icon to be used for the new search experience alert |

## Icon art

> The icon(s) per this request, has the new art been completed?

- [X] Yes
- [ ] No

> If YES, does the new icon art follow all the recommendations from the [Auro Icon Design Guidelines](https://auro.alaskaair.com/foundations/iconography/design-guidelines)?

- [X] Yes
- [ ] No

> If YES, the icon(s) in the request, have they been added to the UiKit Abstract repo?

- [x] Yes
- [ ] No

### Attach exported SVG files to this issue
[notification-active.zip](https://github.com/AlaskaAirlines/Icons/files/6842817/notification-active.zip)

**Comment by gusnaughton** [comment]
Does this icon need to be moved into the fullColor/ namespace in the iconography library? It has a monocolor counterpart of the same design already in ADS.

**Comment by blackfalcon** [comment]
I am assuming that this request is to replace the current mono-color version.

**Comment by arrenkhl** [comment]
> I am assuming that this request is to replace the current mono-color version.

Yes, if that is alright to do.
